name: Documentation
on: [push]


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Documentation
      uses: eagletrt/documentation@main
      with:
        author: Eagletrt           # project author
        project: Eagletrt Project  # project name
        rootfile: branch2            # project title
        folders: ../utils          # path of folders and files you want to document
        version: 1.0.0             # project version
        release: 1.0.0             # project release
        language: c                # language used
        branchname: branch2           # the name of the branch you want to document
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        clean: false 
        branch: docs # The branch the action should deploy to.
        folder: upload # The folder the action should deploy.
